# fly.toml file generated for fly-tailscale-nging-proxy-manager on 2021-10-31T10:59:51+01:00

app = "<my_creative_app_name>"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "ghcr.io/koying/fly-tailscale-nginx:latest"

[env]
  TAILSCALE_HOSTNAME = "fly-tailscale-nginx"
  TAILSCALE_HA_SCHEME = "http"
  TAILSCALE_HA_HOST = "<ha_taiscale_ip>"
  TAILSCALE_HA_PORT = "8123"
  TAILSCALE_AUTHKEY = "<the_tailscale_oneshot_key>"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
